food_list={
  "cereals_and_pulses": [
    "Wheat",
    "Rice",
    "Rava",
    "Bajra",
    "Jowar",
    "Makai",
    "Ragi",
    "Popcorn",
    "Barley",
    "Corn Flakes",
    "Oats",
    "Brown Bread",
    "White Bread",
    "All Dals",
    "Chole",
    "Rajmah",
    "Moong",
    "Matki",
    "Chouli",
    "Vaal",
    "Udad",
    "Soyabean",
    "Sago"
  ],
  "soy_and_soy_products": [
    "Soy chunks",
    "Soy granules",
    "Soy milk (Sofit)"
  ],
  "fruits": [
    "Water Melon",
    "Papaya",
    "Sweet Lime",
    "Musk Melon",
    "Strawberry",
    "Bor",
    "Guava, white",
    "Pear",
    "Orange",
    "Peach",
    "Apple",
    "Apricot",
    "Grape Fruit",
    "Pineapple",
    "Mango",
    "Litchee",
    "Cherries",
    "Jambun",
    "Pomegranate",
    "Plum",
    "Chikoo",
    "Jack Fruit",
    "Karvanda",
    "Figs",
    "Banana",
    "Sitaphal"
  ],
  "dried_fruits": [
    "Raisins",
    "Dates, dried",
    "Apricot"
  ],
  "vegetables": [
    "Cabbage",
    "Lettuce",
    "Mustard leaves",
    "Radish leaves",
    "Spinach",
    "Ash gourd",
    "Bitter gourd",
    "Bottle gourd",
    "Brinjal",
    "Capsicum",
    "Cauliflower",
    "Drumstick",
    "Cucumber",
    "Ladies finger",
    "Parwar",
    "Celery",
    "Kovai",
    "Pumpkin",
    "Papaya (raw)",
    "Tomatoes",
    "Ambatchuka",
    "Shepu",
    "Squash( white pumpkin)",
    "Bathua",
    "Snake gourd",
    "Jackfruit(Raw)",
    "Mayalu",
    "Turnip",
    "Knol- khol",
    "French beans",
    "Broad beans",
    "Onion",
    "Field beans",
    "Cluster beans",
    "Potatoes",
    "Konkoda",
    "Beetroot",
    "Baby corn",
    "Colocasia leaves (green)",
    "Amaranth leaves (red)",
    "Carrot",
    "Radish",
    "Mango green",
    "Drumstick leaves",
    "Fenugreek leaves",
    "Jackfruit seeds",
    "Tapioca",
    "Yam",
    "Sweet potato",
    "Arbi",
    "Suran",
    "Raw banana",
    "Sweet corn",
    "Peas (fresh)",
    "Red gram (tender)"
  ],
  "nuts": [
    "Walnut",
    "Almonds",
    "Cashewnut",
    "Pitaschio",
    "Groundnut",
    "Fresh coconut",
    "Dry coconut"
  ],
  "milk_and_milk_products": [
    "Whole buffalo milk",
    "Skimmed whole buffalo milk",
    "Skimmed whole buffalo milk Paneer",
    "Cow milk",
    "Skimmed cow milk",
    "Skimmed cow milk paneer",
    "Skimmed milk powder",
    "Curd",
    "Cheese",
    "Paneer",
    "Khoa"
  ],
  "egg": [
    "Egg Whole",
    "Egg White",
    "Egg Yolk"
  ],
  "sugar": [
    "Sugar",
    "Jaggery",
    "Honey"
  ],
  "fats": [
    "Oils and fats",
    "Butter",
    "Fresh cream"
  ],
  "meats": [
    "Lean Meat",
    "Meat with fat",
    "Pork",
    "Organ Meat",
    "Pork Ham",
    "Chicken (without Skin)",
    "Lean Fish (Bombay duck, Mackerel, shark, red snapper, tuna, rohu)",
    "Hilsa",
    "Fatty Fish (Pomfret, Salmon, Sardine, Catfish)",
    "Shell Fish (Prawns, Lobsters, Crabs, Squids)"
  ]
}